version: "3.8"

services:

  localstack:
    container_name: laral-aws-localstack
    image:
      localstack/localstack:stable
    ports:
      - "${EDGE_PORT-4566}:4566"
    environment:
      - SERVICES=sqs,sns,s3
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_SECRET_ACCESS_KEY=secret_access_key
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_bootstrap:/etc/localstack/init/ready.d"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - localstack-network

networks:
  localstack-network:
    name: localstack-network